const configuracion = {
    temas: {
        lugares: [
            { imagen: 'TU.png', palabra: 'TU' },
            { imagen: 'YO.png', palabra: 'YO' },
            { imagen: 'PAPÁ.png', palabra: 'PAPÁ' },
            { imagen: 'MAMA.png', palabra: 'MAMA' },
            { imagen: 'IR.png', palabra: 'IR' },
            { imagen: 'JUGAR.png', palabra: 'JUGAR' },
            { imagen: 'ABAJO.png', palabra: 'ABAJO' },
            { imagen: 'AQUÍ.png', palabra: 'AQUÍ' },
            { imagen: 'ARRIBA.png', palabra: 'ARRIBA' },
            { imagen: 'PISCINA.png', palabra: 'PISCINA' },
            { imagen: 'COCHE.png', palabra: 'COCHE' },
            { imagen: 'COLEGIO.png', palabra: 'COLEGIO' },
            { imagen: 'CASA.png', palabra: 'CASA' },
            { imagen: 'CASTILLO.png', palabra: 'CASTILLO' },
            { imagen: 'DENTRO.png', palabra: 'DENTRO' },
            { imagen: 'FUERA.png', palabra: 'FUERA' },
            { imagen: 'GRANJA.png', palabra: 'GRANJA' },
            { imagen: 'LUGARES.png', palabra: 'LUGARES' },
            { imagen: '¿DONDE?.png', palabra: '¿DONDE?' }
        ],
        acciones: [
            { imagen: 'TU.png', palabra: 'TU' },
            { imagen: 'YO.png', palabra: 'YO' },
            { imagen: 'PAPÁ.png', palabra: 'PAPÁ' },
            { imagen: 'MAMA.png', palabra: 'MAMA' },
            { imagen: 'ABIERTO.png', palabra: 'ABIERTO' },
            { imagen: 'AHORA.png', palabra: 'AHORA' },
            { imagen: 'BORRAR.png', palabra: 'BORRAR' },
            { imagen: 'CANTAR.png', palabra: 'CANTAR' },
            { imagen: 'CERRADO.png', palabra: 'CERRADO' },
            { imagen: 'CHARLA_RAPIDA.png', palabra: 'CHARLA RAPIDA' },
            { imagen: 'COGER.png', palabra: 'COGER' },
            { imagen: 'DAR.png', palabra: 'DAR' },
            { imagen: 'DEPORTE.png', palabra: 'DEPORTE' },
            { imagen: 'DESCANSAR.png', palabra: 'DESCANSAR' },
            { imagen: 'DESCRIBIR.png', palabra: 'DESCRIBIR' },
            { imagen: 'DESPUES.png', palabra: 'DESPUES' },
            { imagen: 'DORMIR.png', palabra: 'DORMIR' },
            { imagen: 'DUCHAR.png', palabra: 'DUCHAR' },
            { imagen: 'ELIMINAR.png', palabra: 'ELIMINAR' },
            { imagen: 'ESTAR.png', palabra: 'ESTAR' },
            { imagen: 'ESTAR_3.png', palabra: 'ESTAR' },
            { imagen: 'ESTO.png', palabra: 'ESTO' },
            { imagen: 'GUARDAR.png', palabra: 'GUARDAR' },
            { imagen: 'HACER.png', palabra: 'HACER' },
            { imagen: 'IR.png', palabra: 'IR' },
            { imagen: 'JUGAR.png', palabra: 'JUGAR' },
            { imagen: 'LAVAR_LAS_MANOS.png', palabra: 'LAVAR LAS MANOS' },
            { imagen: 'LAVAR_LOS_DIENTES.png', palabra: 'LAVAR LOS DIENTES' },
            { imagen: 'MAS.png', palabra: 'MAS' },
            { imagen: 'ME_AYUDAS?.png', palabra: 'ME AYUDAS?' },
            { imagen: 'ME_HAGO_CACA.png', palabra: 'ME HAGO CACA' },
            { imagen: 'ME_HAGO_PIS.png', palabra: 'ME HAGO PIS' },
            { imagen: 'ME_LLAMO_JORG.png', palabra: 'ME LLAMO JORG' },
            { imagen: 'ME_LLAMO_JORGE.png', palabra: 'ME LLAMO JORGE' },
            { imagen: 'MORDER.png', palabra: 'MORDER' },
            { imagen: 'NECESITO_LOS_CASCOS.png', palabra: 'NECESITO LOS CASCOS' },
            { imagen: 'NECESITO_TIEMPO.png', palabra: 'NECESITO TIEMPO' },
            { imagen: 'NO.png', palabra: 'NO' },
            { imagen: 'NOVEDADES.png', palabra: 'NOVEDADES' },
            { imagen: 'OCIO.png', palabra: 'OCIO' },
            { imagen: 'OPINIONES.png', palabra: 'OPINIONES' },
            { imagen: 'OTRA_COSA.png', palabra: 'OTRA COSA' },
            { imagen: 'PASEAR.png', palabra: 'PASEAR' },
            { imagen: 'PEGAR.png', palabra: 'PEGAR' },
            { imagen: 'PEINAR.png', palabra: 'PEINAR' },
            { imagen: 'PEQUEÑO.png', palabra: 'PEQUEÑO' },
            { imagen: 'PINTAR.png', palabra: 'PINTAR' },
            { imagen: 'PONER.png', palabra: 'PONER' },
            { imagen: 'PURPURINA.png', palabra: 'PURPURINA' },
            { imagen: 'QUERER.png', palabra: 'QUERER' },
            { imagen: 'QUERER_.png', palabra: 'QUERER' },
            { imagen: 'QUITAR.png', palabra: 'QUITAR' },
            { imagen: 'SALIR.png', palabra: 'SALIR' },
            { imagen: 'SALTAR.png', palabra: 'SALTAR' },
            { imagen: 'SANGRA_LA_NARIZ.png', palabra: 'SANGRA LA NARIZ' },
            { imagen: 'SENTAR.png', palabra: 'SENTAR' },
            { imagen: 'SER.png', palabra: 'SER' },
            { imagen: 'SUBIR.png', palabra: 'SUBIR' },
            { imagen: 'TENER.png', palabra: 'TENER' },
            { imagen: 'TRABAJAR.png', palabra: 'TRABAJAR' },
            { imagen: 'TU_SOLITO.png', palabra: 'TU SOLITO' },
            { imagen: 'VENIR.png', palabra: 'VENIR' },
            { imagen: 'VER.png', palabra: 'VER' },
            { imagen: 'VESTIR.png', palabra: 'VESTIR' },
            { imagen: 'VOLVER.png', palabra: 'VOLVER' },
            { imagen: 'YA_ESTA.png', palabra: 'YA ESTA' }
        ],
        personas: [
            { imagen: 'ABUELA.png', palabra: 'ABUELA' },
            { imagen: 'ABUELO.png', palabra: 'ABUELO' },
            { imagen: 'AMIGO.png', palabra: 'AMIGO' },
            { imagen: 'BEBÉ.png', palabra: 'BEBÉ' },
            { imagen: 'CHICA.png', palabra: 'CHICA' },
            { imagen: 'CHICO.png', palabra: 'CHICO' },
            { imagen: 'GENTE.png', palabra: 'GENTE' },
            { imagen: 'HERMANA.png', palabra: 'HERMANA' },
            { imagen: 'HERMANA_LAURA.png', palabra: 'HERMANA LAURA' },
            { imagen: 'HERMANA_SARA.png', palabra: 'HERMANA SARA' },
            { imagen: 'HERMANO.png', palabra: 'HERMANO' },
            { imagen: 'HOMBRE.png', palabra: 'HOMBRE' },
            { imagen: 'LAURA.png', palabra: 'LAURA' },
            { imagen: 'MAMA.png', palabra: 'MAMA' },
            { imagen: 'MAMA_EVA.png', palabra: 'MAMA EVA' },
            { imagen: 'MUJER.png', palabra: 'MUJER' },
            { imagen: 'MÁS_PERSONAS.png', palabra: 'MÁS PERSONAS' },
            { imagen: 'NIÑA.png', palabra: 'NIÑA' },
            { imagen: 'NIÑO.png', palabra: 'NIÑO' },
            { imagen: 'NIÑOS.png', palabra: 'NIÑOS' },
            { imagen: 'NOSOTROS.png', palabra: 'NOSOTROS' },
            { imagen: 'PAPA_.png', palabra: 'PAPA' },
            { imagen: 'PAPA_ARTURO.png', palabra: 'PAPA ARTURO' },
            { imagen: 'PAPÁ.png', palabra: 'PAPÁ' },
            { imagen: 'PERSONAS.png', palabra: 'PERSONAS' },
            { imagen: 'PILAR.png', palabra: 'PILAR' },
            { imagen: 'PRIMA.png', palabra: 'PRIMA' },
            { imagen: 'PRIMO.png', palabra: 'PRIMO' },
            { imagen: 'SALUDOS.png', palabra: 'SALUDOS' },
            { imagen: 'SARA.png', palabra: 'SARA' },
            { imagen: 'TENGO_9_ANOS.png', palabra: 'TENGO 9 ANOS' },
            { imagen: 'TIA.png', palabra: 'TIA' },
            { imagen: 'TIO.png', palabra: 'TIO' },
            { imagen: 'TU.png', palabra: 'TU' },
            { imagen: 'YO.png', palabra: 'YO' },
            { imagen: 'YO_EN_CABANILLAS.png', palabra: 'YO EN CABANILLAS' },
            { imagen: '¿QUIEN?.png', palabra: '¿QUIEN?' }
        ],
        emociones: [
            { imagen: 'TU.png', palabra: 'TU' },
            { imagen: 'YO.png', palabra: 'YO' },
            { imagen: 'PAPÁ.png', palabra: 'PAPÁ' },
            { imagen: 'MAMA.png', palabra: 'MAMA' },
            { imagen: 'ASUSTADO.png', palabra: 'ASUSTADO' },
            { imagen: 'BIEN.png', palabra: 'BIEN' },
            { imagen: 'CALIENTE.png', palabra: 'CALIENTE' },
            { imagen: 'CANSADO.png', palabra: 'CANSADO' },
            { imagen: 'CON_CALOR.png', palabra: 'CON CALOR' },
            { imagen: 'CON_FRIO.png', palabra: 'CON FRIO' },
            { imagen: 'CONTENTO.png', palabra: 'CONTENTO' },
            { imagen: 'ENFADADO.png', palabra: 'ENFADADO' },
            { imagen: 'ENFERMO.png', palabra: 'ENFERMO' },
            { imagen: 'FRIO.png', palabra: 'FRIO' },
            { imagen: 'LLORANDO.png', palabra: 'LLORANDO' },
            { imagen: 'MAL.png', palabra: 'MAL' },
            { imagen: 'ME_ABURRO.png', palabra: 'ME ABURRO' },
            { imagen: 'ME_DUELE.png', palabra: 'ME DUELE' },
            { imagen: 'ME_ESTOY_PONIENDO_NERVIOSO.png', palabra: 'ME ESTOY PONIENDO NERVIOSO' },
            { imagen: 'ME_GUSTA.png', palabra: 'ME GUSTA' },
            { imagen: 'ME_GUSTA_LA_MUSICA.png', palabra: 'ME GUSTA LA MUSICA' },
            { imagen: 'ME_MOLESTA_EL_RUIDO.png', palabra: 'ME MOLESTA EL RUIDO' },
            { imagen: 'SENTIMIENTOS.png', palabra: 'SENTIMIENTOS' },
            { imagen: 'SENTIR.png', palabra: 'SENTIR' },
            { imagen: 'TE_QUIERO.png', palabra: 'TE QUIERO' },
            { imagen: 'TRANQUILO.png', palabra: 'TRANQUILO' },
            { imagen: 'TRISTE.png', palabra: 'TRISTE' },
            { imagen: '¡AY_QUE_LIO!.png', palabra: '¡AY QUE LIO!' },
            { imagen: '¡ESTE_CHICO!.png', palabra: '¡ESTE CHICO!' },
            { imagen: '¡QUE_PESTE!.png', palabra: '¡QUE PESTE!' },
            { imagen: '¿COMO?.png', palabra: '¿COMO?' },
            { imagen: '¿ME_AYUDAS?.png', palabra: '¿ME AYUDAS?' },
            { imagen: '¿QUE?.png', palabra: '¿QUE?' }
        ],
        objetos: [
            { imagen: 'TU.png', palabra: 'TU' },
            { imagen: 'YO.png', palabra: 'YO' },
            { imagen: 'PAPÁ.png', palabra: 'PAPÁ' },
            { imagen: 'MAMA.png', palabra: 'MAMA' },
            { imagen: 'TU.png', palabra: 'TU' },
            { imagen: 'YO.png', palabra: 'YO' },
            { imagen: 'PAPÁ.png', palabra: 'PAPÁ' },
            { imagen: 'MAMA.png', palabra: 'MAMA' },
            { imagen: 'BABERO.png', palabra: 'BABERO' },
            { imagen: 'BARRIGA.png', palabra: 'BARRIGA' },
            { imagen: 'BATA.png', palabra: 'BATA' },
            { imagen: 'BAUL.png', palabra: 'BAUL' },
            { imagen: 'BIGOTE.png', palabra: 'BIGOTE' },
            { imagen: 'BLANCO.png', palabra: 'BLANCO' },
            { imagen: 'BOCA.png', palabra: 'BOCA' },
            { imagen: 'BRAZO.png', palabra: 'BRAZO' },
            { imagen: 'CABEZA.png', palabra: 'CABEZA' },
            { imagen: 'CARA.png', palabra: 'CARA' },
            { imagen: 'CASCOS.png', palabra: 'CASCOS' },
            { imagen: 'COCODRILO.png', palabra: 'COCODRILO' },
            { imagen: 'CREMA.png', palabra: 'CREMA' },
            { imagen: 'CUCHARA.png', palabra: 'CUCHARA' },
            { imagen: 'CUCHILLO.png', palabra: 'CUCHILLO' },
            { imagen: 'CULO.png', palabra: 'CULO' },
            { imagen: 'DEDOS.png', palabra: 'DEDOS' },
            { imagen: 'DIENTES.png', palabra: 'DIENTES' },
            { imagen: 'GAFAS_DE_SOL.png', palabra: 'GAFAS DE SOL' },
            { imagen: 'GRANDE.png', palabra: 'GRANDE' },
            { imagen: 'LAPIZ.png', palabra: 'LAPIZ' },
            { imagen: 'LENGUA.png', palabra: 'LENGUA' },
            { imagen: 'LIMPIO.png', palabra: 'LIMPIO' },
            { imagen: 'LLENO.png', palabra: 'LLENO' },
            { imagen: 'MANOS.png', palabra: 'MANOS' },
            { imagen: 'NARIZ.png', palabra: 'NARIZ' },
            { imagen: 'OJOS.png', palabra: 'OJOS' },
            { imagen: 'OREJA.png', palabra: 'OREJA' },
            { imagen: 'PLATO.png', palabra: 'PLATO' },
            { imagen: 'PARAGUAS.png', palabra: 'PARAGUAS' },
            { imagen: 'PELO.png', palabra: 'PELO' },
            { imagen: 'PIEDRA.png', palabra: 'PIEDRA' },
            { imagen: 'PIERNA.png', palabra: 'PIERNA' },
            { imagen: 'PIES.png', palabra: 'PIES' },
            { imagen: 'PIOJO.png', palabra: 'PIOJO' },
            { imagen: 'PLAY.png', palabra: 'PLAY' },
            { imagen: 'SERVILLETAS.png', palabra: 'SERVILLETAS' },
            { imagen: 'SILLA.png', palabra: 'SILLA' },
            { imagen: 'SUCIO.png', palabra: 'SUCIO' },
            { imagen: 'TABLET.png', palabra: 'TABLET' },
            { imagen: 'TEJADO.png', palabra: 'TEJADO' },
            { imagen: 'TELEFONO.png', palabra: 'TELEFONO' },
            { imagen: 'TENEDOR.png', palabra: 'TENEDOR' },
            { imagen: 'VACIO.png', palabra: 'VACIO' },
            { imagen: 'VASO.png', palabra: 'VASO' }
        ],
        alimentos: [
            { imagen: 'QUERER.png', palabra: 'QUERER' },
            { imagen: 'AGUA.png', palabra: 'AGUA' },
            { imagen: 'ALIMENTOS.png', palabra: 'ALIMENTOS' },
            { imagen: 'BOCADILLO.png', palabra: 'BOCADILLO' },
            { imagen: 'BOLLO.png', palabra: 'BOLLO' },
            { imagen: 'COCACOLA.png', palabra: 'COCACOLA' },
            { imagen: 'COMER.png', palabra: 'COMER' },
            { imagen: 'ENSALADA.png', palabra: 'ENSALADA' },
            { imagen: 'ESPAGUETIS.png', palabra: 'ESPAGUETIS' },
            { imagen: 'FANTA.png', palabra: 'FANTA' },
            { imagen: 'GALLETAS.png', palabra: 'GALLETAS' },
            { imagen: 'HAMBURGUESA.png', palabra: 'HAMBURGUESA' },
            { imagen: 'LECHE.png', palabra: 'LECHE' },
            { imagen: 'PAN.png', palabra: 'PAN' },
            { imagen: 'PIZZA.png', palabra: 'PIZZA' },
            { imagen: 'PURÉ.png', palabra: 'PURÉ' },
            { imagen: 'SOPA.png', palabra: 'SOPA' },
            { imagen: 'TENGO_HAMBRE.png', palabra: 'TENGO HAMBRE' },
            { imagen: 'TENGO_SED.png', palabra: 'TENGO SED' },
            { imagen: 'TORTILLA.png', palabra: 'TORTILLA' },
            { imagen: 'ZUMO.png', palabra: 'ZUMO' }
        ],
        otros: [
            { imagen: 'ORO.png', palabra: 'ORO' },
            { imagen: 'PLATA.png', palabra: 'PLATA' },
            { imagen: 'NEGRO.png', palabra: 'NEGRO' },
            { imagen: 'MARRÓN.png', palabra: 'MARRÓN' },
            { imagen: 'MORADO.png', palabra: 'MORADO' },
            { imagen: 'COLORES.png', palabra: 'COLORES' },
            { imagen: 'AMARILLO.png', palabra: 'AMARILLO' },
            { imagen: 'ROJO.png', palabra: 'ROJO' },
            { imagen: 'GRIS.png', palabra: 'GRIS' },
            { imagen: 'ROSA.png', palabra: 'ROSA' },
            { imagen: 'FORMAS.png', palabra: 'FORMAS' },
            { imagen: 'AZUL.png', palabra: 'AZUL' },
            { imagen: 'VERDE.png', palabra: 'VERDE' },
            { imagen: 'TODO.png', palabra: 'TODO' },
            { imagen: 'MUCHO.png', palabra: 'MUCHO' },
            { imagen: 'NADA.png', palabra: 'NADA' },
            { imagen: 'POCO.png', palabra: 'POCO' },
            { imagen: 'TIEMPO.png', palabra: 'TIEMPO' },
            { imagen: 'BAJO.png', palabra: 'BAJO' },
            { imagen: 'ALTO.png', palabra: 'ALTO' }
        ],
    },
    temas_info: {
        lugares: { imagen: 'LUGARES.png', palabra: 'LUGARES' },
        acciones: { imagen: 'SALTAR.png', palabra: 'ACCIONES' },
        personas: { imagen: 'YO.png', palabra: 'PERSONAS' },
        emociones: { imagen: 'CONTENTO.png', palabra: 'EMOCIONES' },
        objetos: { imagen: 'CASCOS.png', palabra: 'OBJETOS' },
        alimentos: { imagen: 'PAN.png', palabra: 'ALIMENTOS' },
        otros: { imagen: 'ROJO.png', palabra: 'OTROS' },
    }
};